Add type ignore statements
Mypy claims the assignment is invalid. But since it has worked so
far it can be ignored.
Fixes mypy errors:
```
vula/common.py:418: error: Cannot assign to a type
vula/common.py:418: error: Incompatible types in assignment (expression has type "Type[yamlrepr]", variable has type "Type[yamlrepr_hl]")
vula/common.py:419: error: Cannot assign to a type
vula/common.py:419: error: Incompatible types in assignment (expression has type "Type[jsonrepr]", variable has type "Type[jsonrepr_hl]")
```